version: '3.3'
services:

#################################

# MAIN CONTAINER

################################
  api:
    build:
      context: ./Main # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: mainimg # this is the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: main

#################################

#################################

# API CONTAINER

################################
  api:
    build:
      context: ./API # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: imgapi # this is the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: api
    ports:
      - "8000:5000"
    expose:
      - "5000"

#################################

# TOTOCV CONTAINER

################################
  totocv:
    build:
      context: ./TotoCV # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: totocv-img #the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: toto
    ports:
      - "8001:5000"
    expose:
      - "5000"

#################################

# NOISE(PREPROSS) CONTAINER

################################
  noise:
    build:
      context: ./Edge_Noise # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: noise-img # this is the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: noise
    ports:
      - "8002:5000"
    expose:
      - "5000"

#################################

# MODLE(Shot detect) CONTAINER

################################
  shot_detect:
    build:
      context: ./Edge_Detector # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: shot_detect-img # this is the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: shot_detect
    ports:
      - "8003:5000"
    expose:
      - "5000"









networks:
  appnet: # define appnet network
    driver: bridge

