version: '3.2'
services:
  video:
    hostname: video
    container_name: video
    build:
      context: .
      dockerfile: DockerfileHTML
    expose:
     - "80"
    ports:
     - "80:80"
    volumes:
    - type: volume
      source: feed1
      target: /usr/share/nginx/html/feed1
  encode:
    hostname: encode
    container_name: encode
    build:
      context: .
      dockerfile: DockerfileHLS
    expose:
     - "5000"
    ports:
     - "5000:5000"
    volumes:
    - type: volume
      source: feed1
      target: /srv/feed1
    - type: volume
      source: feed2
      target: /srv/feed2
    - type: volume
      source: feed3
      target: /srv/feed3
  
volumes:
  feed1:
  feed2:
  feed3:
