version: '3.3'
services:

#################################

# Model CONTAINER

################################
  prot:
    build:
      context: ../Edge_DroneProto # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: proto-img # this is the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: proto1
    ports:
      - "8005:5000"
    expose:
      - "5000"
#################################

# Model CONTAINER

################################
  Manager:
    build:
      context: . # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: manner-img # this is the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: Manager
    ports:
      - "8006:5000"
    expose:
      - "5000"
    depends_on:
      - prot

###############################
#Toto 
###############################

  totocv:
    build:
      context: ../TotoCV # this is the absolute path to the app directory
      dockerfile: Dockerfile # this is the name of the Dockerfile in the app directory

    image: totocv-img #the name of the image that will be used by the app service
    networks:
      - appnet # connect to appnet network
    container_name: toto
    ports:
      - "8007:5000"
    expose:
      - "5000"






networks:
  appnet: # define appnet network
    driver: bridge
