version: '3'
services:
  db:
    build:
      context: .
#      dockerfile: Database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: database_storage
        target: /mnt/database_storage
  dev:
    build:
      #context: dev_env_setup
      dockerfile: ./dev_env_setup/Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /mnt/
    tty: true
volumes:
  database_storage: