version: '3'
services:
  db:
    hostname: db
    build:
      context: .
      dockerfile: DockerfileDatabase
    expose:
      - "5432"
    volumes:
      - type: volume
        source: database_storage
        target: /mnt/database_storage
  dev:
    depends_on:
      - db
    hostname: db_dev
    build:
      context: .
      dockerfile: DockerfileDev
    expose:
     - "5000" # flask
    volumes:
      - type: bind # outside source repo
        source: ../
        target: /mnt/
    tty: true

volumes:
  database_storage: