version: '3'
services:
  web:
    build:
      context: .
#      dockerfile: Database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: database_storage
        target: /mnt/database_storage
volumes:
  database_storage: